spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      master:
        jdbc-url: jdbc:mysql://localhost:3306/my_carrot
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        jdbc-url: jdbc:mysql://localhost:3306/my_carrot_replica
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

  data:
     redis:
       host: localhost
       username:
       password:
       port: 6379


  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/carrot
  #    username: root
  #    password: 1234









