spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      master:
        jdbc-url: ENC(mknpSuZ478LFeqB3EsJ6klOplFzq5Wvq9lOCIC4ECCEsp7SGkmbtLoCW/LWygcOqCa+v+nWhJeekB8Hzd+ua07d1PeJMhx89t9jo1GVN7d7ZgnHfz4SfA2n6q5hLu0Px)
        username: ENC(rSMIRNKJ2QXSfQNWaFSsFQ==)
        password: ENC(z+I+Jn3UIfqaWEJOO3ZYbI8snhd/6En/d40rRwCW3IY=)
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        jdbc-url: ENC(iceZ5lH4xYMHyhAte0uMaThjVEmteo1jkIezchoWaui8tWGmO1+QSsgEyKP2n/fD0s3yx+AmyYW8fbgJLsmEvJnW1jZcH+cF7YgVdAUoTwpGIsFbGajtPEdZ8DVYKfcUc2s5oSed0/M=)
        username: ENC(rSMIRNKJ2QXSfQNWaFSsFQ==)
        password: ENC(z+I+Jn3UIfqaWEJOO3ZYbI8snhd/6En/d40rRwCW3IY=)
        driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ENC(/arA+kI6ddz1RItV6voghUPrPyUoMwTOCdQWNNQ8ug3eigHOwrJlHUHH4K41R+XngCTp6/bdv2rEb/g5Mgiw8Qd6cg7pzg5biYg9SzijoMQ1JP12ZaLRuStFtt86XO01)
#    username: ENC(xiS/SCzrq1dVq6qox9+5Bg==)
#    password: ENC(SISyL0Nba50J0z7f2fv/z1pciEKXcwG9HVq5kEmdM9g=)


  session:
#    store-type: redis  # 세션 저장소를 Redis로 설정 86400s
    timeout: 3600s      # 세션 유지 시간 (초 단위, 1시간)
  data:
    redis:
      host: ENC(EhdGStZuFhRl4gHRdQ6YJEXo120kXIuL6FKhGuE0G/3oaRolKCAO/SRgt7Y0BjYxh3i0K3Q7k3zYPyiIwBcIOm4nY/GcW6JZ)
      username: ENC(XluFywcomloscNrlyMhhjg==)
      password: ENC(w88fSqkQJk6JrkYLFRkHzdzr7SCWVyfNCwN7/Ylqt444U/BXMEVMYkYaubM1TylM)
      port: 10819