spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    hikari:
#      master:
#        jdbc-url: ENC(MaQqbvtT427sLmBqYQn2iZpbqkbwHGMLyQVCn8a1GuAcFldPhNi+q8L1oige6WqCx/I7ikxn0N1zEklDnf2yhvIvbRds/xvyD37xUCINiYqX4B16nW+PbKyeXFdgCaUG)
#        username: ENC(7XLXi/w59hcAU2B7KKa/tw==)
#        password: ENC(8M2wgI42LVjGrlU6/qvijcb1cH9/TMegeQ6yfOSyH9I=)
#        driver-class-name: com.mysql.cj.jdbc.Driver
#      slave:
#        jdbc-url: jdbc:mysql://carrot-moa-replica.czioa0eq2ly1.ap-northeast-2.rds.amazonaws.com:3306/carrot_moa
#        username: ENC(7XLXi/w59hcAU2B7KKa/tw==)
#        password: ENC(8M2wgI42LVjGrlU6/qvijcb1cH9/TMegeQ6yfOSyH9I=)
#        driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(MaQqbvtT427sLmBqYQn2iZpbqkbwHGMLyQVCn8a1GuAcFldPhNi+q8L1oige6WqCx/I7ikxn0N1zEklDnf2yhvIvbRds/xvyD37xUCINiYqX4B16nW+PbKyeXFdgCaUG)
    username: ENC(7XLXi/w59hcAU2B7KKa/tw==)
    password: ENC(8M2wgI42LVjGrlU6/qvijcb1cH9/TMegeQ6yfOSyH9I=)


  data:
    redis:
      host: ENC(cZYsn4Gq8W79xoNFBZc5f71jnkNI7ArQs2sQwjxTv3ErnZjzC0Tn/WtU4OXJToZJqNtz2lg4/aFlzFXO6UD/PXTs8tp5ap05)
      username: ENC(Niql4fTzx7wRsCpnyjpfVg==)
      password: ENC(kO3u6vmK3ud+IA2zy7AIGopVM8JxdO3g69y0CWFW3iJRcRcXi2wDosC1kecSJltv)
      port: 10819